### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by so0k**

### CODE REVIEW

**Comment by so0k** [comment]
atlantis plan

**Comment by anubhavmishra** [comment]
@so0k please use atlantis bootstrap mode to test our atlantis. Here is the documentation: https://github.com/hootsuite/atlantis#getting-started. The bootstrap mode will do the rest.

**Comment by so0k** [comment]
@anubhavmishra - I've built an alpine based dockerfile with terraform and atlantis and I'm running ngrok with compose to test my dockerfile.

https://github.com/so0k/atlantis-example/pull/1

Realized I need to have `git` and `openssh` in the docker image, but then it seems it still gets stuck where it tries to `git clone` using the ssh url

**Comment by so0k** [comment]
initial dockerfiles and simulating the `bootstrap` function with compose and bash - https://github.com/honestbee/atlantis/commit/f76eb19e62f2f42aa7441a0c2e6bf235cf9a363b

seems it's not using the token
```cloning git@github.com:so0k/atlantis-example.git: Cloning into '/root/.atlantis/repos/so0k/atlantis-example/1/default'...
Warning: Permanently added 'github.com,192.30.255.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.```

**Comment by anubhavmishra** [comment]
The bootstrap mode is merely to test out atlantis. The bootstrap mode doesn't do any cloning etc. It just forks hootsuite/atlantis-example and creates a pull request. The `atlantis server` command should be the one used in production. Atlantis currently uses the SSH url to clone repositories: https://github.com/hootsuite/atlantis/blob/master/server/workspace.go#L36

**Comment by so0k** [comment]
Correct, I understand that - I created a Docker image and run ngrok container, join the docker container on the ngrok namespace so they talk over local host and get the host url from ngrok, query for github username / MFA code and password which I use to create and get a GitHub Token and finally start the atlantis server (not bootstrap)

https://github.com/honestbee/atlantis/commit/f76eb19e62f2f42aa7441a0c2e6bf235cf9a363b#diff-fd8635a5248b5832a7faf06a8e572e17R37

webhooks work, but it gets stuck when trying to do `atlantis plan` as it is unable to pull the public repo.

**Comment by anubhavmishra** [comment]
@so0k I opened an issue: https://github.com/hootsuite/atlantis/issues/110 to add support for HTTPS cloning.

**Comment by so0k** [comment]
@anubhavmishra - thank you, but I don't understand how the demo / bootstrap works and my setup doesn't? Am I doing something wrong, or should I mount an ssh key in the atlantis server instance and run an ssh-agent to allow the usage of git over ssh?

**Comment by SidecarQA** [comment]
atlantis plan

**Pull request closed without merging**
